package auth.service;
//RuntimeException은 실행중에 나는 exception
public class LoginFailException extends RuntimeException{

}
